language: go
go: 1.13.x

env:
  global:
    - GO111MODULES=on

script: /bin/true

before_deploy: >
  mkdir assets

  for arch in amd64 386; do
    CGO_ENABLED=1 GOOS=linux GOARCH=$arch go build -ldflags '-w -s'
    tar -caf assets/osm-${TRAVIS_TAG}-${arch}.tar.xz osm
  done

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: assets/*
  skip_cleanup: true
  on:
    tags: true
