on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - run: |
          sudo apt update
          sudo apt install --assume-yes gcc-multilib

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
