on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/cargo
        with:
          target: ${{ matrix.target }}
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: true

      - run: echo "TARBALL=osm-${{ github.event.release.tag_name }}-${{ matrix.target }}.tar.xz" >> $GITHUB_ENV
      - run: tar caf $TARBALL --directory=target/${{ matrix.target }}/release osm

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.TARBALL }}
          fail_on_unmatched_files: true
