on:
  release:
    types: [published]

jobs:
  release:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            label: linux-x86_64
          - target: i686-unknown-linux-gnu
            label: linux-x86
          - target: aarch64-unknown-linux-gnu
            label: linux-aarch64
          - target: armv7-unknown-linux-gnueabihf
            label: linux-armv7-eabihf

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/cargo
        with:
          target: ${{ matrix.target }}
          command: build
          args: --release --target ${{ matrix.target }}
          use-cross: true

      - run: echo "TARBALL=osm-${{ github.event.release.tag_name }}-${{ matrix.label }}.tar.xz" >> $GITHUB_ENV
      - run: tar caf $TARBALL --directory=target/${{ matrix.target }}/release osm

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.TARBALL }}
          fail_on_unmatched_files: true
